context:
  instance_type: 't2.micro'
  key_name: 'fastcampus'
  monitoring: true
  associate_public_ip_address: false

remote_states:
  'network':
    organization: 'jawn'
    workspace: 'openvpn-network'
